# Generated by Django 2.0.1 on 2018-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=64)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=64)),
                ('participants', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'User Added Events',
                'ordering': ['city', 'name'],
            },
        ),
    ]
